spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ansimbank?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 12345678
    # driver-class-name: com.mysql.cj.jdbc.Driver   # 생략 가능 (자동 감지)
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  # 필요시 로깅
  # jpa.show-sql: true

server:
  port: 8080
